export const SOURCE_TYPES = [
  "memory",
  "reflection",
  "conversation",
  "journal_entry",
  "check_in",
  "voice_transcript",
  "summary",
  "pattern_report",
];

export const TREND_DIRECTIONS = [
  "emerging",
  "growing",
  "declining",
  "completed",
  "stable",
];

export const REPORT_WINDOWS = {
  monthly: 30,
  quarterly: 90,
  annual: 365,
};

export const DEFAULT_THRESHOLD = {
  exactMatch: 0.85,
  semanticMatch: 0.7,
  supportMatch: 0.58,
};

export const NARRATIVE_DEFINITIONS = [
  {
    family: "agency",
    label: "Transitioning Into Leadership",
    key: "narrative.transitioning_into_leadership",
    kind: "identity",
    keywords: [
      "leadership",
      "leader",
      "take charge",
      "responsibility",
      "mentor",
      "manage",
      "guidance",
      "initiative",
      "decision",
      "owning it",
      "step up",
    ],
    supportingPatterns: [
      "validation seeking",
      "self-criticism",
      "avoidance",
      "procrastination",
      "people pleasing",
      "overthinking",
    ],
    supportingEmotions: ["confidence", "anxiety", "courage", "relief"],
    supportingGoals: ["lead", "decide", "take responsibility", "speak up", "mentor"],
    themes: ["agency", "visibility", "responsibility"],
  },
  {
    family: "resilience",
    label: "Recovering From Burnout",
    key: "narrative.recovering_from_burnout",
    kind: "regulation",
    keywords: [
      "burnout",
      "burnt out",
      "exhausted",
      "drained",
      "depleted",
      "overloaded",
      "shutdown",
      "numb",
      "rest",
      "recover",
      "overwhelm",
    ],
    supportingPatterns: [
      "avoidance",
      "withdrawal",
      "procrastination",
      "perfectionism",
      "self-criticism",
      "overthinking",
    ],
    supportingEmotions: ["anxiety", "relief", "sadness", "overwhelm"],
    supportingGoals: ["rest", "recover", "slow down", "reduce load", "sleep"],
    themes: ["energy", "recovery", "stability"],
  },
  {
    family: "relational",
    label: "Learning Emotional Boundaries",
    key: "narrative.learning_emotional_boundaries",
    kind: "relationship",
    keywords: [
      "boundary",
      "boundaries",
      "say no",
      "limit",
      "protect",
      "overextend",
      "enough",
      "permission",
      "clear with",
    ],
    supportingPatterns: [
      "people pleasing",
      "conflict avoidance",
      "emotional distancing",
      "validation seeking",
    ],
    supportingEmotions: ["anger", "relief", "confidence", "fear"],
    supportingGoals: ["say no", "protect time", "state needs", "be clear"],
    themes: ["self-protection", "relational clarity", "capacity"],
  },
  {
    family: "meaning",
    label: "Trusting Intuition",
    key: "narrative.trusting_intuition",
    kind: "identity",
    keywords: [
      "intuition",
      "gut",
      "instinct",
      "inner knowing",
      "listen to myself",
      "trust myself",
      "I know",
      "signal",
    ],
    supportingPatterns: [
      "overthinking",
      "validation seeking",
      "future fixation",
      "perfectionism",
    ],
    supportingEmotions: ["confidence", "calm", "trust", "relief"],
    supportingGoals: ["listen inward", "act on insight", "trust the signal"],
    themes: ["inner authority", "discernment", "self-trust"],
  },
  {
    family: "creative",
    label: "Creative Self-Expression",
    key: "narrative.creative_self_expression",
    kind: "identity",
    keywords: [
      "creative",
      "expression",
      "write",
      "art",
      "share",
      "voice",
      "make",
      "create",
      "play",
      "publish",
    ],
    supportingPatterns: [
      "perfectionism",
      "withdrawal",
      "self-criticism",
      "people pleasing",
    ],
    supportingEmotions: ["joy", "curiosity", "confidence", "relief"],
    supportingGoals: ["create", "share work", "use my voice", "publish"],
    themes: ["expression", "visibility", "aliveness"],
  },
  {
    family: "agency",
    label: "Building Self-Trust",
    key: "narrative.building_self_trust",
    kind: "identity",
    keywords: [
      "self-trust",
      "trust myself",
      "keep promises",
      "follow through",
      "reliable",
      "consistent",
      "my own pace",
      "believe in myself",
    ],
    supportingPatterns: [
      "validation seeking",
      "self-criticism",
      "procrastination",
      "overthinking",
    ],
    supportingEmotions: ["confidence", "hope", "calm", "trust"],
    supportingGoals: ["follow through", "keep promises", "act consistently"],
    themes: ["reliability", "inner authority", "agency"],
  },
  {
    family: "relational",
    label: "Repairing Relationships",
    key: "narrative.repairing_relationships",
    kind: "relationship",
    keywords: [
      "repair",
      "rebuild",
      "apologize",
      "forgive",
      "mend",
      "trust",
      "connection",
      "honest",
      "conversation",
    ],
    supportingPatterns: [
      "conflict avoidance",
      "fear of abandonment",
      "emotional distancing",
      "people pleasing",
    ],
    supportingEmotions: ["sadness", "relief", "confidence", "care"],
    supportingGoals: ["repair", "tell the truth", "reconnect", "listen"],
    themes: ["repair", "trust", "connection"],
  },
  {
    family: "stability",
    label: "Moving From Survival To Stability",
    key: "narrative.moving_from_survival_to_stability",
    kind: "transition",
    keywords: [
      "survival",
      "stable",
      "stability",
      "safe",
      "secure",
      "grounded",
      "routine",
      "consistent",
      "support",
      "settle",
    ],
    supportingPatterns: [
      "anxiety",
      "overwhelm",
      "withdrawal",
      "avoidance",
      "procrastination",
    ],
    supportingEmotions: ["anxiety", "relief", "calm", "hope"],
    supportingGoals: ["create routine", "feel safe", "reduce chaos", "stabilize"],
    themes: ["safety", "routine", "capacity"],
  },
  {
    family: "agency",
    label: "Reclaiming Agency",
    key: "narrative.reclaiming_agency",
    kind: "identity",
    keywords: [
      "agency",
      "choice",
      "decide",
      "decision",
      "control",
      "take action",
      "claim",
      "responsibility",
      "my life",
    ],
    supportingPatterns: [
      "avoidance",
      "people pleasing",
      "validation seeking",
      "future fixation",
    ],
    supportingEmotions: ["confidence", "anger", "courage", "hope"],
    supportingGoals: ["choose", "decide", "act", "claim ownership"],
    themes: ["self-direction", "choice", "agency"],
  },
  {
    family: "resilience",
    label: "Integrating Grief And Loss",
    key: "narrative.integrating_grief_and_loss",
    kind: "transition",
    keywords: [
      "grief",
      "grieving",
      "loss",
      "mourning",
      "sadness",
      "goodbye",
      "let go",
      "missing",
      "hurt",
    ],
    supportingPatterns: [
      "withdrawal",
      "emotional distancing",
      "avoidance",
      "conflict avoidance",
    ],
    supportingEmotions: ["sadness", "relief", "fear", "hope"],
    supportingGoals: ["let go", "mourn", "remember", "heal"],
    themes: ["loss", "meaning", "integration"],
  },
];

export const EMOTION_LEXICON = [
  { label: "anxiety", keywords: ["anxious", "anxiety", "worried", "worry", "nervous", "panic", "stress", "overwhelmed"] },
  { label: "shame", keywords: ["ashamed", "shame", "embarrassed", "humiliated", "exposed"] },
  { label: "anger", keywords: ["angry", "anger", "furious", "resentful", "irritated", "annoyed"] },
  { label: "joy", keywords: ["joy", "happy", "delighted", "excited", "pleased", "glad"] },
  { label: "confidence", keywords: ["confident", "capable", "certain", "sure", "steady", "trust myself"] },
  { label: "hope", keywords: ["hope", "hopeful", "optimistic", "possible"] },
  { label: "relief", keywords: ["relief", "relieved", "lighter", "calm"] },
  { label: "sadness", keywords: ["sad", "sadness", "down", "hurt", "lonely", "empty", "grief"] },
  { label: "trust", keywords: ["trust", "trust myself", "trusting", "safe", "secure"] },
  { label: "overwhelm", keywords: ["overwhelmed", "overload", "too much", "swamped", "drained"] },
  { label: "curiosity", keywords: ["curious", "curiosity", "explore", "wonder", "play"] },
];

export const BELIEF_SHIFT_PHRASES = [
  "used to believe",
  "no longer believe",
  "now believe",
  "starting to believe",
  "learning that",
  "realizing that",
  "i think differently",
];

export const VALUE_SHIFT_PHRASES = [
  "i value",
  "what matters to me",
  "prioritize",
  "important to me",
  "care more about",
  "i want to spend",
  "this matters",
];

export const IDENTITY_SHIFT_PHRASES = [
  "i am becoming",
  "i am no longer",
  "i am learning to",
  "i am starting to",
  "i see myself as",
  "i want to be",
];

export const EMOTIONAL_MATURATION_PHRASES = [
  "can feel",
  "without acting",
  "pause before",
  "stay with",
  "tolerate",
  "regulate",
  "ask for help",
  "set boundaries",
  "notice before reacting",
  "hold space",
];

export const EXPERIMENTATION_PHRASES = [
  "trying",
  "experimenting",
  "practice",
  "test",
  "testing",
  "attempting",
  "working on",
  "learning to",
  "starting to",
];

export const CHAPTER_SEQUENCE = [
  { number: 1, title: "Recognizing the Pattern" },
  { number: 2, title: "Experimentation" },
  { number: 3, title: "Identity Shift" },
  { number: 4, title: "Integration" },
];
